# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints1.xdc

# Block Designs: bd/Axi_SPI/Axi_SPI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Axi_SPI || ORIG_REF_NAME==Axi_SPI} -quiet] -quiet

# IP: bd/Axi_SPI/ip/Axi_SPI_jtag_axi_0_0/Axi_SPI_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Axi_SPI_jtag_axi_0_0 || ORIG_REF_NAME==Axi_SPI_jtag_axi_0_0} -quiet] -quiet

# IP: bd/Axi_SPI/ip/Axi_SPI_MySPI_0_0/Axi_SPI_MySPI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Axi_SPI_MySPI_0_0 || ORIG_REF_NAME==Axi_SPI_MySPI_0_0} -quiet] -quiet

# IP: bd/Axi_SPI/ip/Axi_SPI_clk_wiz_0/Axi_SPI_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Axi_SPI_clk_wiz_0 || ORIG_REF_NAME==Axi_SPI_clk_wiz_0} -quiet] -quiet

# IP: bd/Axi_SPI/ip/Axi_SPI_rst_clk_wiz_100M_0/Axi_SPI_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Axi_SPI_rst_clk_wiz_100M_0 || ORIG_REF_NAME==Axi_SPI_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/Axi_SPI/ip/Axi_SPI_reset_inv_0_0/Axi_SPI_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Axi_SPI_reset_inv_0_0 || ORIG_REF_NAME==Axi_SPI_reset_inv_0_0} -quiet] -quiet

# XDC: /home/zach/Lab_4_194BB/Lab_4_194BB.gen/sources_1/bd/Axi_SPI/Axi_SPI_ooc.xdc
