# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zach/Lab_4_194BB/Lab_4_194BB.srcs/sources_1/bd/Axi_SPI/ip/Axi_SPI_jtag_axi_0_0/Axi_SPI_jtag_axi_0_0.xci
# IP: The module: 'Axi_SPI_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zach/Lab_4_194BB/Lab_4_194BB.gen/sources_1/bd/Axi_SPI/ip/Axi_SPI_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'Axi_SPI_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/zach/Lab_4_194BB/Lab_4_194BB.gen/sources_1/bd/Axi_SPI/ip/Axi_SPI_jtag_axi_0_0/Axi_SPI_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Axi_SPI_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/zach/Lab_4_194BB/Lab_4_194BB.srcs/sources_1/bd/Axi_SPI/ip/Axi_SPI_jtag_axi_0_0/Axi_SPI_jtag_axi_0_0.xci
# IP: The module: 'Axi_SPI_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zach/Lab_4_194BB/Lab_4_194BB.gen/sources_1/bd/Axi_SPI/ip/Axi_SPI_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'Axi_SPI_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/zach/Lab_4_194BB/Lab_4_194BB.gen/sources_1/bd/Axi_SPI/ip/Axi_SPI_jtag_axi_0_0/Axi_SPI_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Axi_SPI_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
